### PR TITLE
fix multiple clocks at the same time

### LINKED ISSUE #44: Prevent running clock for multiple activities at once
javascript only (check)

### PR DESCRIPTION
**Pull request by microstudi**
- fixes #44 
- also fixes an annoying bug in the admin when editing dates for an activity

### CODE REVIEW

File: app/forms/decidim/time_tracker/admin/activity_form.rb [hunk 1]
```diff
@@ -10,8 +10,8 @@ class ActivityForm < Decidim::Form
         translatable_attribute :description, String
 
         attribute :active, Boolean
-        attribute :start_date, Decidim::Attributes::LocalizedDate
-        attribute :end_date, Decidim::Attributes::LocalizedDate
+        attribute :start_date, Decidim::Attributes::TimeWithZone
+        attribute :end_date, Decidim::Attributes::TimeWithZone
```
Comment (verarojman) [inline app/forms/decidim/time_tracker/admin/activity_form.rb:14]: ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

Comment (verarojman) [reply app/forms/decidim/time_tracker/admin/activity_form.rb:14]: It was horrible to deal with this when editing dates

**Review by verarojman — APPROVED** [review]
Looks wonderful! The world is a little bit better now :')
